Sprint 9
yourchencore666/ImageFeed pull request #3
Opened 2022-12-13 14:25 UTC by yourchencore666

- Добавлен экран картинки при выборе ячейки
- Добавлен зум картинки
- Добавлен шаринг картинки
- Добавлен экран профиля, сверстанный кодом
- Добавлена навигация между экранами через TabBar

Спасибо за ревью!

2022-12-14 06:17 UTC, ABashkirova commented
Смотри, кнопка находится по горизонтали - по центру, у нее фиксированные размеры 50 на 50.

Твои констрейнты говорят, что по краям контейнера у нее отступы по 162, при этом ширину кнопки ты не фиксируешь. Что это значит: если ширина экрана будет сильно больше чем на сториборде, кнопку эти два констрейнта растянут, и она станет широкой и овальной, вместо круга. Наоборот: если экран будет уже чем эти значения, то кнопку сплющит. 

Чтобы этого избежать, строгие констрейнты по бокам надо удалить, и заменить на констрейнт "по центральной оси X", также добавить констрейнт на ширину кнопки (или apect ratio 1к1, если так больше нравится)
<img width="695" alt="Снимок экрана 2022-12-14 в 08 13 59" src="https://user-images.githubusercontent.com/20269264/207520272-339d55cf-5dd1-448e-9c89-cbd94d9e006b.png">

2022-12-14 06:43 UTC, ABashkirova requested changes

2022-12-14 06:43 UTC, ABashkirova commented on ImageList/ImagesListViewController.swift
> +            let indexPath = sender as! IndexPath // Делаем преобразование типа для аргумента sender (мы ожидаем, что там будет indexPath)
такие force cast'ы часто можно увидеть в навигационном коде сторибордов даже в продакшене, однако я рекомендую не делать такое в учебных/тестовых задачах. Предлагаю использовать конструкции `if let a = optionalA as? A, let b = optionalB as? B { }`

Такой код для потенциального работодателя может показаться небезопасным, могут придраться. Ну и лично я предпочитаю в продакшен даже тут такое не писать :)

2022-12-14 06:43 UTC, ABashkirova commented on ImageList/SingleImageViewController.swift
> +    @IBOutlet weak var scrollView: UIScrollView!
давай сделаем приватными до тех пор, пока не понадобится публичный доступ

2022-12-14 06:43 UTC, ABashkirova commented on ImageList/SingleImageViewController.swift
> +    @IBAction func didTapShareButton(_ sender: UIButton) {
тоже приватная функция

2022-12-14 06:43 UTC, ABashkirova commented on Profile/ProfileViewController.swift
> +        logoutButton.setImage(UIImage(systemName: "ipad.and.arrow.forward"), for: .normal)
лайк за SF иконку :)

2022-12-14 06:43 UTC, ABashkirova commented on Profile/ProfileViewController.swift
> +    // MARK: - Public Properties
если не понадобились марки, то стоит их удалять, как и весь остальной неиспользуемый код :)

2022-12-14 08:35 UTC, yourchencore666 commented
Правки внёс, спасибо!!!

2022-12-14 20:40 UTC, ABashkirova commented on ImageList/ImagesListViewController.swift
> +            if let viewController = segue.destination as? SingleImageViewController, let indexPath = sender as? IndexPath {
🫶

2022-12-15 06:28 UTC, yourchencore666 commented on ImageList/ImagesListViewController.swift
> +            if let viewController = segue.destination as? SingleImageViewController, let indexPath = sender as? IndexPath {
что это значит?)))

2022-12-15 06:29 UTC, merged

2022-12-15 08:59 UTC, ABashkirova commented on ImageList/ImagesListViewController.swift
> +            if let viewController = segue.destination as? SingleImageViewController, let indexPath = sender as? IndexPath {
спасибо, что учел комментарий :)